version: '3'

services:
  node:
    container_name: nodejs-node
    image: node:16-alpine3.14
    tty: true
    volumes:
      - ./app:/app
    networks:
      nodejs-network:
        ipv4_address: 192.168.20.2

networks:
  nodejs-network:
    ipam:
      config:
        - subnet: 192.168.20.0/28